!$F_DISTRIBUTION= "v2"

!if %not(%variable_exists("$CLASSES"))
    !include ../Templates/Classes2.cuml
!endif

class F_Distribution {
    ..private class fields..
    - $static_field(_Min) : float = 0
    ..private instance fields..
    - {field} _Parameters: dict(str -> float OR int)
    - {field} _Cached: dict(str -> float OR int)
    ..getter / setter properties..
    + Degree1: float > 0 OR int > 0
    + Degree2: float > 0 OR int > 0
    ..getter properties..
    # Mean: float > 0 OR None
    # Var: float > 0 OR None
    # Sigma: float > 0 OR None
    # Skew: float > 0 OR None
    # Kurt: float > 0 OR None
    __
    ..special methods..
    __init__(Degree1, Degree2): float > 0 OR int > 0, float > 0 OR int > 0 -> None
    ..private methods..
    - _pdf(x): float OR int -> float
    - _cdf(x): float OR int -> float OR int
}