@startuml statistics_lib_components

!if %not(%variable_exists("$COMPONENTS"))
    !include ./Templates/Components2.cuml
!endif

title Components Diagram of the Library statistics_lib. $generated()

!if $is_not_defined("$BASE_FUNCTIONS")
    !include ./base_functions/base_functions_components.iuml
!endif

!if $is_not_defined("$ORDERED_FUNCTIONS")
    !include ./ordered_functions/ordered_functions_components.iuml
!endif

!if $is_not_defined("$SPECIAL_FUNCTIONS")
    !include ./special_functions/special_functions_components.iuml
!endif

!if $is_not_defined("$DATA_CLASSES")
    !include ./data_classes/data_classes_components.iuml
!endif

base_functions <-------- data_classes : uses

ordered_functions <-------- data_classes : uses

!if $is_not_defined("$DISTRIBUTION_CLASSES")
    !include ./distribution_classes/distribution_classes_components.iuml
!endif

special_functions <-------- distribution_classes : uses

!if $is_not_defined("$STAT_TESTS")
    !include ./stat_tests/stat_tests_components.iuml
!endif

data_classes <---- stat_tests : uses

distribution_classes <------ stat_tests : uses

!if $is_not_defined("$INVERSE_DISTRIBUTIONS")
    !include ./inverse_distributions/inverse_distributions_components.iuml
!endif

distribution_classes <|-- inverse_distributions : extends

@enduml