!$INVERSE_DISTRIBUTIONS = "v2"

!if %not(%variable_exists("$COMPONENTS"))
    !include ../Templates/Components2.cuml
!endif

$module(inverse_distributions) {
    $class(InverseGaussian)

    $class(InverseGamma)

    $class(InverseChiSquared)

    $class(ScaledInverseChiSquared)

    $class(Cauchy)

    $class(Levy)
}