@startuml data_classes_class

!if %not(%variable_exists("$CLASSES"))
    !include ../Templates/Classes2.cuml
!endif

title Class Diagram of the Module statistics_lib.data_classes. $generated()

!if $is_not_defined("$STATISTICS1D")
    !include ./statistics1d.iuml
!endif

!if $is_not_defined("$STATISTICS2D")
    !include ./statistics2d.iuml
!endif

Statistics1D "2" -o "1" Statistics2D

@enduml